[package]
name = "rusty-html-extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hp = "1.0.0"
html2text = "0.5.1"
zip = "0.6.4"
